<?xml version="1.0" encoding="utf-8"?><Database Name="LocationService" Class="LINQClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=LocationService;Integrated Security=True" SettingsObjectName="SocketServer.Properties.Settings" SettingsPropertyName="LocationServiceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="locationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="altitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="longtitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lastupdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Location_User" Member="Users" ThisKey="locationId" OtherKey="locationId" Type="User" />
      <Association Name="User_Location" Member="User" ThisKey="userid" OtherKey="userid" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="locationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ip" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Location" Member="Locations" ThisKey="userid" OtherKey="userid" Type="Location" />
      <Association Name="Location_User" Member="Location" ThisKey="locationId" OtherKey="locationId" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
</Database>